# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity: 
                class: VctModBundle:User
                property: email
    firewalls:
        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /
                check_path: /login_check
                
                username_parameter: _email
                password_parameter: _password
                
            logout:
                path: /logout
                target: /
                invalidate_session: false
                
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

#cifra la contraseña de usuarios    
    encoders:
        Vct\ModBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/modulo, roles: ROLE_USER }